### ISSUE TITLE
フッター実装

### ISSUE THREAD

**Issue by dninomiya** [camp-team/team-training#1]
## PC

![image](https://user-images.githubusercontent.com/5842851/88472625-df10af00-cf4f-11ea-801d-c984cae02726.png)

## SP

![image](https://user-images.githubusercontent.com/5842851/88472629-edf76180-cf4f-11ea-874c-a025cdc75a1f.png)

**Comment by mihye1128** [comment]
@chamaboy 
すみません！先ほどの修正、確認が甘かったところがあったので、またお手隙の際にご対応お願いします。
```scss
.form__input {
  padding: 4px 35px 4px 20px; // 私が修正例で出した上下の余白がおかしかった
  // opacity: 50%; ← colorを透明度で指定したので、これは外してください。
}
```
